name: Startup a bot.

on:
  push:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Change Directory
      run: cd src
    
    - name: Start Docker
      run: docker-compose --env-file .env up
    
